### ISSUE TITLE
Testnet panick

### ISSUE THREAD

**Issue by garethtdavies** [ZcashFoundation/parity-zcash#58]
The closing of #12 did indeed solve the issue of connecting to peers however I now see the following issue on testnet. Running current master 43aace6d711fb73b9e70b2b0039cfe8f309166f3 

```
./target/release/zebra --data-dir=/home/gareth/.zebra-testnet --testnet
2019-06-27 16:20:41  INFO sync Processed 1000 blocks in 2.60 seconds (384.24 blk/s).    Peers: 3 (act: 3, idl: 0, bad: 0).      Chain: [sch:0 > req:237 > vfy:43 > db:1001]
2019-06-27 16:20:44  INFO sync Processed 1000 blocks in 2.94 seconds (340.25 blk/s).    Peers: 3 (act: 3, idl: 0, bad: 0).      Chain: [sch:0 > req:80 > vfy:0 > db:2001]
thread '<unnamed>' panicked at 'slice index starts at 1 but ends at 0', src/libcore/slice/mod.rs:2566:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: rust_begin_unwind
             at src/libstd/panicking.rs:308
   7: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   8: core::slice::slice_index_order_fail
             at src/libcore/slice/mod.rs:2566
   9: bitcrypto::pghr13::verify
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2735
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2818
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/slice/mod.rs:2543
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/liballoc/vec.rs:1677
             at crypto/src/pghr13.rs:89
  10: verification::sprout::verify
             at verification/src/sprout.rs:65
  11: verification::accept_transaction::JoinSplitVerification::check
             at verification/src/accept_transaction.rs:582
             at verification/src/accept_transaction.rs:655
  12: verification::accept_transaction::TransactionAcceptor::check
             at verification/src/accept_transaction.rs:80
  13: rayon::iter::plumbing::Folder::consume_iter
             at verification/src/accept_chain.rs:79
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libcore/result.rs:637
             at verification/src/accept_chain.rs:79
             at /home/gareth/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/fold.rs:122
             at /home/gareth/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:176
  14: rayon::iter::plumbing::bridge_producer_consumer::helper
             at /home/gareth/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:108
             at /home/gareth/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:418
  15: std::panicking::try::do_call
             at /home/gareth/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-1.0.3/src/iter/plumbing/mod.rs:413
             at /home/gareth/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/join/mod.rs:122
             at /home/gareth/.cargo/registry/src/github.com-1ecc6299db9ec823/rayon-core-1.4.1/src/job.rs:113
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panic.rs:309
             at /rustc/3c235d5600393dfe6c36eeed34042efad8d4f26e/src/libstd/panicking.rs:293
  16: <unknown>
             at src/libpanic_abort/lib.rs:29
fish: “./target/release/zebra --data-d…” terminated by signal SIGABRT (Abort)
```

Additional details:

```
cargo --version
cargo 1.35.0 (6f3e9c367 2019-04-04)
```

I also removed the old testnet directory and was able to reliably reproduce this behaviour.

**Comment by garethtdavies** [comment]
My mistake, I was on the wrong local branch :sleeping: It does indeed work :smile:
